<?php
/**
 * Ninja to Gravity import form template.
 * 
 * @package ninja-to-gravity
 */

?>

<div class="gform-settings__content">
	<form method="post" enctype="multipart/form-data" class="gform_settings_form">
		<?php wp_nonce_field( 'gf_import_forms', 'gf_import_forms_nonce' ); ?>
		<div class="gform-settings-panel gform-settings-panel--full">
			<header class="gform-settings-panel__header"><legend class="gform-settings-panel__title"><?php esc_html_e( 'Import Ninja Forms', 'ninja-to-gravity' ); ?></legend></header>
			<div class="gform-settings-panel__content">
				<div class="gform-settings-description">
					<?php
					echo esc_html__( 'Select the Ninja Forms export files you would like to import. Please make sure your files have the .nff extension, and that they were generated by the Ninja Forms Export form tool. When you click the import button below, Gravity Forms will import the forms.', 'ninja-to-gravity' );
					?>
				</div>
				<table class="form-table">
					<tr valign="top">

						<th scope="row">
							<label for="gf_import_file"><?php esc_html_e( 'Select Files', 'ninja-to-gravity' ); ?></label> <?php gform_tooltip( 'import_select_file' ); ?>
						</th>
						<td><input type="file" name="gf_import_file[]" id="gf_import_file" multiple /></td>
					</tr>
					<?php if ( ! empty( $ninja_forms ) ) : ?>
						<tr valign="top">
							<th scope="row">
								<label for="gf_import_id"><?php esc_html_e( 'Select Form', 'ninja-to-gravity' ); ?></label> <?php gform_tooltip( 'import_select_file' ); ?>
							</th>
							<td>
								<select name="gf_import_id" id="gf_import_id">
									<option value="" selected disabled><?php echo esc_html__( 'Select a form', 'ninja-to-gravity' ); ?></option>
									<?php foreach ( $ninja_forms as $form ) : ?>
										<option value="<?php echo esc_attr( $form->get_id() ); ?>"><?php echo esc_html( $form->get_setting( 'title' ) ); ?></option>
									<?php endforeach; ?>
								</select> 
							</td>
						</tr>
					<?php endif; ?>

				</table>
				<br /><br />
				<input type="submit" value="<?php esc_attr_e( 'Import', 'ninja-to-gravity' ); ?>" name="import_forms" class="button large primary" />
			</div>
		</div>
	</form>
</div>
